version: '2'
services:
  graphite:
    image: zxbtony/grafana_graphite
    environment:
      - GF_SERVER_ROOT_URL=$EXT_IP
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - CARBON_CACHE_ENABLED=true
      - ENABLE_LOGROTATION=true
    volumes:
      - graphite_data:/var/lib/graphite
      - grafana_data:/var/lib/grafana
      - grafana_log:/var/log/grafana
    ports:
      - 3000:3000
      - 80:80
      - 2003:2003
volumes:
  graphite_data:
  grafana_data:
  grafana_log:
